### ISSUE TITLE
Publish detekt jar

### ISSUE THREAD

**Issue by guuilp** [twitter/compose-rules#50]
**Context**
The project I work uses Detekt via CLI. We use the CLI because is faster when working with Git Hooks - we don't need to invoke Gradle and configure 500 modules to just analyze files statically during a commit.

**Feature request**
Publish detekt jar in order to allow detekt cli users to use your compose-rules plugin.

**Describe the solution you'd like**
Loved your compose rules and really want to use them, but I'd need a jar to call it like this:

```
./.detekt/detekt-cli-$VERSION/bin/detekt-cli \
    --config quality/detekt/default-config.yml \
    --plugins .detekt/detekt-formatting-$VERSION.jar,.detekt/custom-detekt-rules.jar,.detekt/compose-rules-$COMPOSE_RULE_VERSION.jar \
```

Our `custom-detekt-rules.jar` is built like this: `./gradlew :detekt:custom-detekt-rules:build`, so I thought maybe you could add something like this on the workflow and publish it on the GitHub assets on the release.

**Comment by kenyee** [comment]
you can grab this off maven central too:
https://mvnrepository.com/artifact/com.twitter.compose.rules/detekt/0.0.3
(not sure why that search doesn't show the latest 0.0.6 build though)

**Comment by mrmans0n** [comment]
This is probably also doable via github actions so we can automatically add them to the releases, will need to look into that. Meanwhile, what @kenyee said, a maven repo is nothing more than a series of subdirectories with stuff in them (like the rules detekt jar)

**Comment by guuilp** [comment]
Just tried with this jar from mvnrepository but got this exception:

```
java.util.concurrent.CompletionException: java.lang.IllegalStateException: Analyzing /Users/guilherme.pereira/Projects/---/flippernoop/src/main/java/com/facebook/flipper/plugins/network/FlipperOkhttpInterceptor.kt led to an exception.
Location: java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
The original exception message was: java.lang.NoClassDefFoundError: com/twitter/rules/core/detekt/TwitterDetektRule
Running detekt '1.21.0' on Java '11.0.16.1+1-LTS' on OS 'Mac OS X'
If the exception message does not help, please feel free to create an issue on our GitHub page.
    at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
    at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
    at java.base/java.util.concurrent.CompletableFuture.uniExceptionally(CompletableFuture.java:990)
    at java.base/java.util.concurrent.CompletableFuture$UniExceptionally.tryFire(CompletableFuture.java:970)
    at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
    at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1705)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.IllegalStateException: Analyzing /Users/guilherme.pereira/Projects/---/flippernoop/src/main/java/com/facebook/flipper/plugins/network/FlipperOkhttpInterceptor.kt led to an exception.
Location: java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
The original exception message was: java.lang.NoClassDefFoundError: com/twitter/rules/core/detekt/TwitterDetektRule
Running detekt '1.21.0' on Java '11.0.16.1+1-LTS' on OS 'Mac OS X'
If the exception message does not help, please feel free to create an issue on our GitHub page.
    at io.gitlab.arturbosch.detekt.core.AnalyzerKt.throwIllegalStateException(Analyzer.kt:163)
    at io.gitlab.arturbosch.detekt.core.AnalyzerKt.access$throwIllegalStateException(Analyzer.kt:1)
    at io.gitlab.arturbosch.detekt.core.Analyzer$runAsync$tasks$1$2.invoke(Analyzer.kt:88)
    at io.gitlab.arturbosch.detekt.core.Analyzer$runAsync$tasks$1$2.invoke(Analyzer.kt:88)
    at io.gitlab.arturbosch.detekt.core.TaskPoolKt.recover$lambda-1(TaskPool.kt:14)
    at java.base/java.util.concurrent.CompletableFuture.uniExceptionally(CompletableFuture.java:986)
    ... 6 more
Caused by: java.util.concurrent.CompletionException: java.lang.NoClassDefFoundError: com/twitter/rules/core/detekt/TwitterDetektRule
    at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
    at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
    at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1702)
    ... 3 more
Caused by: java.lang.NoClassDefFoundError: com/twitter/rules/core/detekt/TwitterDetektRule
    at com.twitter.compose.rules.detekt.TwitterComposeRuleSetProvider.instance(TwitterComposeRuleSetProvider.kt:15)
    at io.gitlab.arturbosch.detekt.core.Analyzer$analyze$activeRuleSetsToRuleSetConfigs$3.invoke(Analyzer.kt:107)
    at io.gitlab.arturbosch.detekt.core.Analyzer$analyze$activeRuleSetsToRuleSetConfigs$3.invoke(Analyzer.kt:107)
    at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:210)
    at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:170)
    at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:194)
    at kotlin.sequences.TransformingSequence$iterator$1.hasNext(Sequences.kt:214)
    at kotlin.sequences.FlatteningSequence$iterator$1.ensureItemIterator(Sequences.kt:311)
    at kotlin.sequences.FlatteningSequence$iterator$1.hasNext(Sequences.kt:303)
    at kotlin.collections.MapsKt__MapsKt.putAll(Maps.kt:424)
    at kotlin.collections.MapsKt__MapsKt.toMap(Maps.kt:592)
    at kotlin.collections.MapsKt__MapsKt.toMap(Maps.kt:586)
    at io.gitlab.arturbosch.detekt.core.rules.RuleSetsKt.associateRuleIdsToRuleSetIds(RuleSets.kt:51)
    at io.gitlab.arturbosch.detekt.core.Analyzer.analyze(Analyzer.kt:110)
    at io.gitlab.arturbosch.detekt.core.Analyzer.access$analyze(Analyzer.kt:31)
    at io.gitlab.arturbosch.detekt.core.Analyzer$runAsync$tasks$1$1.invoke(Analyzer.kt:85)
    at io.gitlab.arturbosch.detekt.core.Analyzer$runAsync$tasks$1$1.invoke(Analyzer.kt:83)
    at io.gitlab.arturbosch.detekt.core.TaskPoolKt.task$lambda-0(TaskPool.kt:12)
    at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
    ... 3 more
```

Maybe this is related to how the jar was built?

**Comment by guuilp** [comment]
This is the `FlipperOkhttpInterceptor.kt` file:

```kotlin
class FlipperOkhttpInterceptor : Interceptor {
    override fun intercept(chain: Interceptor.Chain): Response {
        return chain.proceed(chain.request())
    }
}
```

**Comment by kenyee** [comment]
it's composed of multiple jar files...you need the -core jar as well (though in this older version it's called "common"):
https://mvnrepository.com/artifact/com.twitter.compose.rules/common
That's because it has support for ktlint/detekt w/ a common codeset for the actual rules.

**Comment by guuilp** [comment]
Got it! Maybe if we change this line to `api project(':core-common')`, it'll build and publish a "fat jar"?

https://github.com/twitter/compose-rules/blob/main/core-detekt/build.gradle#L9

**Comment by kenyee** [comment]
that's actually not supposed to be an api and exposed like that...sorry.

**Comment by digitalbuddha** [comment]
Maybe you can try to make the fat jar yourself https://www.baeldung.com/gradle-fat-jar from what I gather it will simply be adding both dependencies to same gradle module and then generating an output https://www.baeldung.com/gradle-fat-jar

**Comment by mrmans0n** [comment]
Ok, I've just merged #65. This is only partially addressing what you want, because it's still not done in CI automatically.

But if you download the repo and run `./gradlew :rules:detekt:shadowJar` you'll get a file called `rules/detekt/build/libs/detekt-0.0.10-SNAPSHOT-all.jar` (or whatever version we currently have in the repo) which is a fat jar. 

You can then run it via:
```
detekt -p path-to-the-repo/rules/detekt/build/libs/detekt-0.0.10-SNAPSHOT-all.jar -c your-config-path/detekt.yml
```

Also don't forget to enable them in detekt.yml like [is mentioned here](https://twitter.github.io/compose-rules/#enabling-rules).

**Comment by guuilp** [comment]
Huuuuuge thanks @mrmans0n !

I'm running just as you suggested on the beginning, with all the jars, so no need to rush on the fat jar publication.

Nice work 💯

**Comment by mrmans0n** [comment]
So the automatic pipeline to publish the fat jars in releases is alive and working 🎊 

You can see detekt and ktlint's fatjars in [the new 0.0.11 release](https://github.com/twitter/compose-rules/releases/tag/v0.0.11) 💃 

I'll put up something in the docs for folks that want to run it in CI to use these.
